### ISSUE TITLE
introduction vignette possible mistake

### ISSUE THREAD

**Issue by EmmalineSheahan** [hannahlowens/voluModel#2]
In line 294, is it supposed to be envelopeModelBottom being masked, since envelopeModelSurface was already masked earlier in the script?:

# Put it all together, bottom
envelopeModelBottom <- temperaturePresence * AOUpresence
envelopeModelSurface <- mask(crop(envelopeModelSurface, studyRegion), mask = studyRegion)

**Comment by hannahlowens** [comment]
Yep, you're right. Just fixed and pushed.
